name: Publish to NPM

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check for master branch
        run:
          echo $REF
          if [ "$REF" != "refs/heads/master" ]; then
            echo "Wrong ref"
            exit 1
          fi
        env:
          REF: ${{ github.ref }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '19.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies and build 🔧
        run: yarn && yarn run build
      - name: Publish package on NPM 📦
        run: yarn publish --new-version $(git describe --tags `git rev-list --tags --max-count=1`)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
